# Prefix (mac-safe)
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# Vim copy mode
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Splits
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

# Reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"
